// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using berua.DAL;

namespace berua.DAL.Migrations
{
    [DbContext(typeof(BeruaContext))]
    partial class BeruaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("berua.DAL.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarUrl");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("berua.DAL.AccountKey", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<byte>("SocialNetworkType");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountKeys");
                });

            modelBuilder.Entity("berua.DAL.Subscription", b =>
                {
                    b.Property<string>("AccountKeyId");

                    b.Property<int>("UserId");

                    b.HasKey("AccountKeyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("berua.DAL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateRegistration");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("berua.DAL.AccountKey", b =>
                {
                    b.HasOne("berua.DAL.Account", "Account")
                        .WithMany("AccountKeys")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("berua.DAL.Subscription", b =>
                {
                    b.HasOne("berua.DAL.AccountKey", "AccountKey")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AccountKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("berua.DAL.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
